<?xml version="1.0" encoding="utf-8"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0" ns="http://www.tei-c.org/ns/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <start>
    <element name="TEI">
      <attribute name="n"/>
      <externalRef href="https://raw.githubusercontent.com/biblhertz/hwgw-data/refs/heads/schema/relaxng/register_header.rng"/>
      <element name="text">
        <element name="body">
          <empty/>
        </element>
        <element name="back">
          <element name="div">
            <attribute name="xml:id">
              <value>index-bib</value>
            </attribute>
            <element name="head">
              <value>Literaturverzeichnis</value>
            </element>
            <element name="listBibl">
              <oneOrMore>
                <ref name="lit_entry"/>
              </oneOrMore>
            </element>
            <element name="listBibl">
              <oneOrMore>
                <ref name="nh_entry"/>
              </oneOrMore>
            </element>
          </element>
        </element>
      </element>
    </element>
  </start>
  <div>
    <define name="lit_entry">
      <element name="bibl">
        <attribute name="xml:id">
          <data type="string">
            <param name="pattern" xml:space="preserve">bib-.+</param>
          </data>
        </attribute>
        <element name="title">
          <attribute name="type">
            <value>short</value>
          </attribute>
          <text/>
        </element>
        <element name="bibl">
          <attribute name="type">
            <value>full</value>
          </attribute>
          <attribute name="xml:space">
            <value>preserve</value>
          </attribute>
          <choice>
            <ref name="monograph"/>
            <ref name="inBook"/>
            <ref name="journalArticle"/>
            <mixed>
              <element name="author">
                <optional>
                  <attribute name="ref"/>
                </optional>
                <text/>
              </element>
              <optional>
                <element name="title">
                  <attribute name="level">
                    <value>a</value>
                  </attribute>
                  <text/>
                </element>
              </optional>
              <element name="title">
                <attribute name="level">
                  <value>m</value>
                </attribute>
                <text/>
              </element>
              <choice>
                <element name="title">
                  <attribute name="level">
                    <value>j</value>
                  </attribute>
                  <text/>
                </element>
                <group>
                  <element name="pubPlace">
                    <text/>
                  </element>
                  <element name="publisher">
                    <text/>
                  </element>
                </group>
              </choice>
              <element name="date">
                <text/>
              </element>
              <optional>
                <element name="biblScope">
                  <attribute name="unit">
                    <value>part</value>
                  </attribute>
                  <text/>
                </element>
              </optional>
              <optional>
                <element name="biblScope">
                  <attribute name="unit">
                    <value>page</value>
                  </attribute>
                  <text/>
                </element>
              </optional>
            </mixed>
          </choice>
        </element>
      </element>
    </define>
    <define name="monograph">
      <mixed>
        <oneOrMore>
          <element name="author">
            <optional>
              <attribute name="ref"/>
            </optional>
            <text/>
          </element>
        </oneOrMore>
        <element name="title">
          <attribute name="level">
            <value>m</value>
          </attribute>
          <text/>
        </element>
        <zeroOrMore>
          <element name="editor">
            <text/>
          </element>
        </zeroOrMore>
        <optional>
          <element name="title">
            <attribute name="level">
              <value>s</value>
            </attribute>
            <text/>
          </element>
          <element name="biblScope">
            <attribute name="unit">
              <value>volume</value>
            </attribute>
            <text/>
          </element>
        </optional>
        <element name="pubPlace">
          <text/>
        </element>
        <element name="publisher">
          <text/>
        </element>
        <element name="date">
          <text/>
        </element>
      </mixed>
    </define>
    <define name="inBook">
      <mixed>
        <oneOrMore>
          <element name="author">
            <optional>
              <attribute name="ref"/>
            </optional>
            <text/>
          </element>
        </oneOrMore>
        <element name="title">
          <attribute name="level">
            <value>a</value>
          </attribute>
          <text/>
        </element>
        <element name="title">
          <attribute name="level">
            <value>m</value>
          </attribute>
          <text/>
        </element>
        <zeroOrMore>
          <element name="editor">
            <text/>
          </element>
        </zeroOrMore>
        <optional>
          <element name="title">
            <attribute name="level">
              <value>s</value>
            </attribute>
            <text/>
          </element>
          <element name="biblScope">
            <attribute name="unit">
              <value>volume</value>
            </attribute>
            <text/>
          </element>
        </optional>
        <element name="pubPlace">
          <text/>
        </element>
        <element name="publisher">
          <text/>
        </element>
        <element name="date">
          <text/>
        </element>
      </mixed>
    </define>
    <define name="journalArticle">
      <mixed>
        <element name="author">
          <optional>
            <attribute name="ref"/>
          </optional>
          <text/>
        </element>
        <element name="title">
          <attribute name="level">
            <value>a</value>
          </attribute>
          <text/>
        </element>
        <element name="title">
          <attribute name="level">
            <value>j</value>
          </attribute>
          <text/>
        </element>
        <element name="date">
          <text/>
        </element>
        <optional>
          <element name="biblScope">
            <attribute name="unit">
              <value>volume</value>
            </attribute>
            <text/>
          </element>
        </optional>
        <element name="biblScope">
          <attribute name="unit">
            <value>page</value>
          </attribute>
          <text/>
        </element>
      </mixed>
    </define>
    <define name="nh_entry">
      <element name="bibl">
        <attribute name="xml:id">
          <data type="string">
            <param name="pattern" xml:space="preserve">bib-nh.+</param>
          </data>
        </attribute>
        <element name="title">
          <attribute name="type">
            <value>short</value>
          </attribute>
          <data type="string">
            <param name="pattern" xml:space="preserve">Notizheft \d+</param>
          </data>
        </element>
        <element name="bibl">
          <attribute name="type">
            <value>full</value>
          </attribute>
          <attribute name="xml:space">
            <value>preserve</value>
          </attribute>
          <mixed>
            <element name="author">
              <optional>
                <attribute name="ref"/>
              </optional>
              <text/>
            </element>
            <element name="title">
              <attribute name="level">
                <value>m</value>
              </attribute>
              <text/>
            </element>
            <element name="pubPlace">
              <text/>
            </element>
            <element name="publisher">
              <text/>
            </element>
            <element name="ref">
              <attribute name="type">
                <value>doi</value>
              </attribute>
              <attribute name="target"/>
              <text/>
            </element>
          </mixed>
        </element>
      </element>
    </define>
  </div>
</grammar>
