<?xml version="1.0" encoding="utf-8"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0" ns="http://www.tei-c.org/ns/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <start>
      <element name="TEI">
          <attribute name="n"/>
          <externalRef href="register_header.rng"/>
          <element name="text">
              <element name="body">
                  <empty/>
              </element>
              <element name="back">
                  <element name="div">
                      <attribute name="xml:id">
                          <value>index-pers</value>
                      </attribute>
                      <element name="head">
                          <value>Personenverzeichnis</value>
                      </element>
                      <element name="listPerson">
                          <oneOrMore>
                              <element name="person">
                                  <attribute name="xml:id"/>
                                  <element name="persName">
                                      <attribute name="type">
                                          <value>main</value>
                                      </attribute>
                                      <text/>
                                  </element>
                                  <optional>
                                      <element name="persName">
                                          <attribute name="type">
                                              <value>nee</value>
                                          </attribute>
                                          <text/>
                                      </element>
                                  </optional>
                                  <zeroOrMore>
                                      <element name="persName">
                                          <attribute name="type">
                                              <value>alternative</value>
                                          </attribute>
                                          <text/>
                                      </element>
                                  </zeroOrMore>
                                  <choice>
                                      <group>
                                          <optional>
                                              <element name="birth">
                                                  <choice>
                                                      <group>
                                                          <attribute name="when">
                                                              <data type="string">
                                                                  <param name="pattern" xml:space="preserve">[12]\d\d\d</param>
                                                              </data>
                                                          </attribute>
                                                          <empty/>
                                                      </group>
                                                      <group>
                                                          <attribute name="when">
                                                              <data type="string">
                                                                  <param name="pattern" xml:space="preserve">0\d\d\d|-\d+</param>
                                                              </data>
                                                          </attribute>
                                                          <text/>
                                                      </group>
                                                      <text/>
                                                  </choice>
                                              </element>
                                          </optional>
                                          <optional>
                                              <element name="death">
                                                  <choice>
                                                      <group>
                                                          <attribute name="when">
                                                              <data type="string">
                                                                  <param name="pattern" xml:space="preserve">[12]\d\d\d</param>
                                                              </data>
                                                          </attribute>
                                                          <empty/>
                                                      </group>
                                                      <group>
                                                          <attribute name="when">
                                                              <data type="string">
                                                                  <param name="pattern" xml:space="preserve">0\d\d\d|-\d+</param>
                                                              </data>
                                                          </attribute>
                                                          <text/>
                                                      </group>
                                                      <text/>
                                                  </choice>
                                              </element>
                                          </optional>
                                      </group>
                                      <element name="note">
                                          <text/>
                                      </element>
                                  </choice>

                                  <optional>
                                      <element name="idno">
                                          <attribute name="type">
                                              <value>GND</value>
                                          </attribute>
                                          <text/>
                                      </element>
                                  </optional>
                                  <optional>
                                      <element name="idno">
                                          <attribute name="type">
                                              <value>ULAN</value>
                                          </attribute>
                                          <text/>
                                      </element>
                                  </optional>
                                  <optional>
                                      <element name="idno">
                                          <attribute name="type">
                                              <value>VIAF</value>
                                          </attribute>
                                          <text/>
                                      </element>
                                  </optional>
                              </element>
                          </oneOrMore>
                      </element>
                  </element>
              </element>
          </element>
      </element>
  </start>
</grammar>
