<?xml version="1.0" encoding="UTF-8"?>
<!-- Stand: 12.03.2016 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3.org/XML/1998/namespace" >

  <xs:attribute name="id">
    <xs:annotation>
      <xs:documentation>(identifier) provides a unique identifier for the element bearing the attribute.</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
        <xs:union memberTypes="xml:elementIdType xml:renditionIdType">
        </xs:union>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="lang" type="xs:language">
    <xs:annotation>
      <xs:documentation>language</xs:documentation>
    </xs:annotation>
  </xs:attribute>

    <xs:attribute name="space">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="preserve"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:simpleType name="elementIdType">
        <xs:restriction base="xml:elementKeyType">
            <xs:pattern value="[^#].*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="elementLinkType">
        <xs:restriction base="xml:elementKeyType">
            <xs:pattern value="#.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="elementKeyType">
        <xs:restriction base="xs:string">
            <!-- modern page numbers -->
            <xs:pattern value="#?s\d\d-pg\d+"/>
            <!-- original page numbers -->
            <xs:pattern value="#?s\d\d-ed-pg\d+"/>
            <xs:pattern value="#?s\d\d-ed-pg[IVXL]+"/>

            <!-- chapters and paragraphs -->
            <xs:pattern value="#?s\d\d-(app|ed|in)-ch(-\d+)+(-p-\d+)?"/>

            <!-- comments and paragraphs in comments -->
            <xs:pattern value="#?s\d\d-(app|ed|in)-comment-\d+(-p-\d+)?"/>

            <!-- images -->
            <xs:pattern value="#?s\d\d-(app|ed|in)-img-\d+(-desc)?"/>

            <!-- original footnotes -->
            <xs:pattern value="#?s\d\d-ed-pg\d+-note-\d+(-p-\d+)?"/>
            <xs:pattern value="#?s\d\d-ed-pg[IVXL]+-note-\d+(-p-\d+)?"/>

            <!-- original quotes and lines -->
            <xs:pattern value="#?s\d\d-ed-ch(-\d+)+-p-\d+-q-\d+(-l-\d+)"/>

            <!-- modern footnotes in apparat -->
            <xs:pattern value="#?s\d\d-app-ch(-\d+)+-note-\d+(-p-\d+)?"/>

            <!-- document text -->
            <xs:pattern value="#?s\d\d-doc-\d+(-p-\d+)?"/>

            <!-- document metadata -->
            <xs:pattern value="#?s\d\d-doc-\d+-desc2?"/>

            <!-- document footnotes -->
            <xs:pattern value="#?s\d\d-doc-\d+-note-\d+(-p-\d+)?"/>

            <!-- document comments -->
            <xs:pattern value="#?s\d\d-doc-comment-\d+(-p-\d+)?"/>

            <!-- GND entries -->
            <xs:pattern value="#?gnd-[0-9\-X]*|#?gnd-local-[0-9a-zA-Z\-]*"/>
            <!-- bibl entries -->
            <xs:pattern value="#?bib-[0-9a-zA-Z\-.]*"/>
            <!-- art entries -->
            <xs:pattern value="#?object-[0-9a-zA-Z\-]*"/>
            <!-- index file main element -->
            <xs:pattern value="#?index-(bib|obj|org|pers|place)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="renditionIdType">
        <xs:restriction base="xml:renditionKeyType">
            <xs:pattern value="[^#].*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="renditionLinkType">
        <xs:restriction base="xml:renditionKeyType">
            <xs:pattern value="#.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="renditionKeyType">
        <xs:restriction base="xs:string">
            <xs:pattern value="#?antiqua"/>
            <xs:pattern value="#?block"/>
            <xs:pattern value="#?center"/>
            <xs:pattern value="#?fraktur"/>
            <xs:pattern value="#?indent"/>
            <xs:pattern value="#?italic"/>
            <xs:pattern value="#?left"/>
            <xs:pattern value="#?right"/>
            <xs:pattern value="#?underlined"/>
            <xs:pattern value="#?superscript"/>
            <xs:pattern value="#?spaced"/>
            <xs:pattern value="#?double_underlined"/>
            <xs:pattern value="#?HW_document_description"/>
            <xs:pattern value="#?s\d\d_.*"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
